In [15]:
#libraries
import pandas as pd
import numpy as np
import geopandas as gpd
import osmnx as ox

In [139]:
# Load PA data into pandas dataframe
pa_data = gpd.read_file('/Users/leonardo/Desktop/Tesi/LTSBikePlan/data/grafo_web.geojson')
pa_data = pa_data[["desvia","sensouni", "tipo_arco", "geometry"]]
column_mapping = {
    "desvia": "name",
    "sensouni": "oneway",
    "tipo_arco": "highway"
}
pa_data = pa_data.rename(columns=column_mapping)

oneway_mapping = {0: False, 1: True}
pa_data['oneway'] = pa_data['oneway'].map(oneway_mapping)
# names_streets = pa_data['name']
# # Find values that appear more than once in the 'name' column
# duplicated_names = pa_data['name'][pa_data['name'].duplicated()]

# # Print the duplicated values
# #print(duplicated_names)

# # Count the occurrences of duplicated values
# duplicated_counts = duplicated_names.value_counts()

# # Print the counts of duplicated values
# #print(duplicated_counts)
# print(duplicated_counts["VIA AL DESERT"])

pa_data.head()

,name,oneway,highway,geometry
0,VIA A. DEGASPERI,False,,"LINESTRING (664581.810 5101530.000, 664579.690..."
1,VIA DELLA CERVARA,False,,"LINESTRING (664552.810 5104142.000, 664561.560..."
2,VIA MISSIONI AFRICANE,False,,"LINESTRING (664411.690 5105140.000, 664403.060..."
3,VIA DEL PRAOL,False,PRINCIPALE,"LINESTRING (659229.870 5103833.070, 659234.620..."
4,PIAZZA NATALE TOMMASI,False,PRINCIPALE,"LINESTRING (666490.250 5105400.000, 666490.480..."

In [129]:
# OSM data for Trento
location = "Trento, Territorio Val d'Adige, Provincia di Trento, Trentino-Alto Adige/SÃ¼dtirol, Italy"
G = ox.graph_from_place(location, network_type='bike')

# Convert the graph into a geopandas dataframe
tn_nodes, tn_edges = ox.graph_to_gdfs(G)

# List of major road types
major_roads = ['primary', 'primary_link', 'secondary', 'secondary_link', 'tertiary',
               'tertiary_link', 'trunk', 'trunk_link', 'residential', 'cycleway',
               'living_street', 'unclassified', 'motorway', 'motorway_link',
               'pedestrian', 'steps', 'track']

In [137]:
filtered_edges = tn_edges[tn_edges['highway'].isin(major_roads)].copy()
filtered_edges.head()

                            osmid              name       highway  oneway  \
u       v          key
9191982 2454602411 0    306341971     Via al Desert      tertiary   False
        9199373    0    306341971     Via al Desert      tertiary   False
9192420 8493240409 0     23717214               NaN    trunk_link    True
        432436406  0     37332639               NaN  unclassified    True
9192593 9204090    0    306205725  Via Hubert Jedin      tertiary    True

                       reversed   length  \
u       v          key
9191982 2454602411 0      False   57.315
        9199373    0       True   66.875
9192420 8493240409 0      False   12.805
        432436406  0      False   31.570
9192593 9204090    0      False  288.630

                                                                 geometry  \
u       v          key
9191982 2454602411 0    LINESTRING (11.11699 46.04997, 11.11687 46.04946)
        9199373    0    LINESTRING (11.11699 46.04997, 11.11701 46.050...
9192420 8493240409 0    LINESTRING (11.11122 46.07698, 11.11108 46.076...
        432436406  0    LINESTRING (11.11122 46.07698, 11.11111 46.077...
9192593 9204090    0    LINESTRING (11.11710 46.05215, 11.11701 46.052...

                       lanes maxspeed junction service bridge  ref width  \
u       v          key
9191982 2454602411 0     NaN      NaN      NaN     NaN    NaN  NaN   NaN
        9199373    0     NaN      NaN      NaN     NaN    NaN  NaN   NaN
9192420 8493240409 0       1       50      NaN     NaN    NaN  NaN   NaN
        432436406  0       1       50      NaN     NaN    NaN  NaN   NaN
9192593 9204090    0       2       50      NaN     NaN    NaN  NaN   NaN

                       access tunnel
u       v          key
9191982 2454602411 0      NaN    NaN
        9199373    0      NaN    NaN
9192420 8493240409 0      NaN    NaN
        432436406  0      NaN    NaN
9192593 9204090    0      NaN    NaN

In [136]:
# Filter tn_edges to include only major roads
filtered_edges = tn_edges[tn_edges['highway'].isin(major_roads)].copy()

# Convert lists in the "name" column to tuples
filtered_edges.loc[:, 'name'] = filtered_edges['name'].apply(lambda x: tuple(x) if isinstance(x, list) else x)

# Get distinct values and their counts in the 'name' column
distinct_names_counts = filtered_edges['name'].value_counts()

# Print the distinct values and their counts
print(distinct_names_counts["Via al Desert"])

22